name:                sokoban
version:             0.1.0.0
github:              "ecthiender/sokoban"
license:             BSD3
author:              "Anon Ray"
maintainer:          "Anon Ray"
copyright:           "2018 Anon Ray"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ecthiender/sokoban#readme>

dependencies:
- base >= 4.7 && < 5
- process
- gloss
- gloss-juicy

library:
  source-dirs: src

executables:
  sokoban:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -O2
    dependencies:
    - sokoban

tests:
  sokoban-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sokoban
